services:
  php:
    build: .docker/php
    ports:
      - 5173:5173
      - 9000:9000
    environment:
      XDEBUG_CONFIG: "remote_host=127.0.0.1"
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ./src:/var/www:cached
    networks:
      - traefik

  nginx:
    image: nginx
    volumes:
      - ./src:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - traefik

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'pawns'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql-db8:/var/lib/mysql'
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  mysql-db8:
    driver: local